### ISSUE TITLE
 Implement the program

### ISSUE THREAD

**Issue by teocarla** [p-r-m-n/esp32-61850-socket#1]
Hello, I would like to implement the program created by you on two ESP32 Wroom boards. In which program did you write the code? I wanted to put it in the Arduino IDE, do you think it works? Thank you!

**Comment by p-r-m-n** [comment]
> Hello, I would like to implement the program created by you on two ESP32 Wroom boards. In which program did you write the code? I wanted to put it in the Arduino IDE, do you think it works? Thank you!

Hi, each folder is an ESP-IDF project, created with VSCODE and Espressif extension for VSCODE. As the GOOSE protocol of IEC 61850 has some time requirements regarding the packets, i created the HAL to send or receive these packets through ethernet only. So, each project should be flashed on a esp32 with ethernet (ESP32-Ethernet-Kit, WT32-ETH01, T-ETH-Lite, etc..). Since each board has its own ethernet pin config, you should edit the project "sdkconfig" (through menuconfig or editing directly inside the project folder) to match your ethernet pin configuration.

I don't know how to export the project to arduino IDE, but i think you would have to start with the "CMakeLists.txt" file inside the "main" folder of each project. This file contains the directory of the source files and the include files necessary to build each program. I think it would work, but don't know how long can take.

**Comment by teocarla** [comment]
Thank you for your answer. Can you please tell me if on the HW connection side you connected each ESP32 board to the computer via the micro usb cable, or if you did it differently? Also after you connected the boards, in order to use enthernet to transmit data you just have to edit the "sdkconfig" project to put the pin configuration in the program, or should I do something else? Thanks a lot!!!

**Comment by p-r-m-n** [comment]
> Thank you for your answer. Can you please tell me if on the HW connection side you connected each ESP32 board to the computer via the micro usb cable, or if you did it differently? Also after you connected the boards, in order to use enthernet to transmit data you just have to edit the "sdkconfig" project to put the pin configuration in the program, or should I do something else? Thanks a lot!!!

The boards i used didn't come with usb port, it was necessary to use a USB to TTL converter to flash the code on each esp. After flashing the code, it's not necessary for the boards to be connected to a pc, but they have to be powered on and in the same network with the PLC's used.

In order to use ethernet, it's only necessary to modify the pin config of the project "sdkconfig" (note that each folder is a project).
